---
title: "Clocks on the Web"
format:
  revealjs:
    theme: simple
    slide-number: true
    transition: fade
    scrollable: true
    smaller: true
---

## High Level

- **What:**
  - Is time in sync on the web?
  - Do people lie about their date?
  - How adopted is ICMP clocksync?

- **Why:**
  - I want a way to infer accurate remote time for arbitrary hosts.
  - For "timing" requests, like attempting to "hit" endpoints at exact times in their time.
  - And general curiosity on how in sync the time on the web is.

- **Goal:**
  - Infer the time of a remote host, and obtain a broad understanding of how in sync time is on the web.
  
Maybe:

  - Cross validate using NTP server
  - Cross validate using ICMP clockdiff
  - Provide evidence for design choices and quantify improvements

# How I'm Measuring

## ICMP Clocksync

When a client sends a timestamp request:

1. Client records local send time $t_0$
1. Server receives packet and writes its receive time $t_1$
1. Server sends reply and writes transmit time $t_2$
1. Client receives reply at time $t_3$

It's easy with `clockdiff`!

```bash
╰─○ sudo clockdiff case.edu  
..................................................
host=case.edu rtt=53(11)ms/31ms delta=14ms/14ms Tue Feb 24 12:01:05 2026
```

I made a `zmap` module to scan the web for `ICMP Timestamp` respondees by forking their `ICMP ping` example module. Then I got a `zmap` allowed VPS, and I am working on doing an internet scan!

::: {.callout-note collapse="true"}
## Derivation

And you do math to figure out the time

Then 

$\text{RTT} = t_3 - t_0$

$t_1 = t_0 + d_1 + \text{offset}$

$p = t_2 - t_1$

$t_2 = t_1 + p$

$t_3 = t_2 + d_2 - \text{offset}$

$\text{offset} = \frac{(t_1 - t_0) + (t_2 - t_3)}{2}$
:::

---

## HTTP `Date:` "edge"

```bash
╰─○ curl https://case.edu -I
HTTP/2 200 
server: Apache
cache-control: max-age=0, no-cache, must-revalidate
accept-ranges: bytes
content-type: text/html
via: 1.1 varnish, 1.1 varnish
strict-transport-security: max-age=31536000
date: Tue, 24 Feb 2026 16:53:00 GMT <--- their date??
x-cache: MISS, MISS
x-cache-hits: 0, 0
x-timer: S1771951980.188655,VS0,VE141
vary: User-Agent
```

1. Send many requests right at the edge of the second
1. So you send at $0.995, 0.996, 0.997, 0.998, 0.999, 1.000, 1.001, \ldots$
1. See which was the first for the `Date:` to change. Let's say we received it at $0.998$ in our time
1. Assume symmetric network latency (not true, but NTP also assumes this, and hopefully it's good enough). Let's say $\text{rtt}=0.1$
1. So, $0.998 - \frac{\text{RTT}}{2} = 0.998 - 0.05 = 0.948$ is when the server sent the response
1. If we assume the server's time is exactly $1.000$ when it sent it, the offset is $1.000 - 0.948 = 0.052 = 52 ms$

Catch: I am having trouble showing this actually works :(

**Plan**:

1. Get it working
1. Scan the internet

---

## NTP server?

Directly figure out how off people's clocks are by joining an NTP pool.

---


## Offset Samples (1)

| offset_micros | server | send_at | receive_at |
| ---: | --- | --- | --- |
| -65,000  | 2026-02-23 23:08:16+00:00 | 2026-02-23 23:08:07.935038+00:00 | 2026-02-23 23:08:16.658929+00:00 |
| -61,000  | 2026-02-23 23:08:16+00:00 | 2026-02-23 23:08:07.939001+00:00 | 2026-02-23 23:08:16.540371+00:00 |
| -49,000  | 2026-02-23 23:08:16+00:00 | 2026-02-23 23:08:07.954052+00:00 | 2026-02-23 23:08:16.659046+00:00 |
| -47,000  | 2026-02-23 23:08:16+00:00 | 2026-02-23 23:08:07.956866+00:00 | 2026-02-23 23:08:16.428203+00:00 |
| -42,000  | 2026-02-23 23:08:16+00:00 | 2026-02-23 23:08:07.958000+00:00 | 2026-02-23 23:08:16.436138+00:00 |
| -36,000  | 2026-02-23 23:08:16+00:00 | 2026-02-23 23:08:07.964002+00:00 | 2026-02-23 23:08:16.660144+00:00 |
| -24,000  | 2026-02-23 23:08:16+00:00 | 2026-02-23 23:08:07.976001+00:00 | 2026-02-23 23:08:16.788346+00:00 |
| -19,000  | 2026-02-23 23:08:16+00:00 | 2026-02-23 23:08:07.981001+00:00 | 2026-02-23 23:08:16.540152+00:00 |
| -12,000  | 2026-02-23 23:08:16+00:00 | 2026-02-23 23:08:07.988001+00:00 | 2026-02-23 23:08:16.540599+00:00 |
| -6,000   | 2026-02-23 23:08:16+00:00 | 2026-02-23 23:08:07.994001+00:00 | 2026-02-23 23:08:16.214161+00:00 |
| -4,000   | 2026-02-23 23:08:16+00:00 | 2026-02-23 23:08:07.996002+00:00 | 2026-02-23 23:08:16.765900+00:00 |
| | | |
| -964,000 | 2026-02-23 23:08:17+00:00 | 2026-02-23 23:08:07.653807+00:00 | 2026-02-23 23:08:17.443776+00:00 |
| | | |
| -959,000 | 2026-02-23 23:08:17+00:00 | 2026-02-23 23:08:07.654081+00:00 | 2026-02-23 23:08:17.219679+00:00 |
| -952,000 | 2026-02-23 23:08:17+00:00 | 2026-02-23 23:08:07.654391+00:00 | 2026-02-23 23:08:17.217739+00:00 |
| -926,000 | 2026-02-23 23:08:17+00:00 | 2026-02-23 23:08:07.655531+00:00 | 2026-02-23 23:08:17.352536+00:00 |
| -915,000 | 2026-02-23 23:08:17+00:00 | 2026-02-23 23:08:07.656005+00:00 | 2026-02-23 23:08:17.218836+00:00 |
| -905,000 | 2026-02-23 23:08:17+00:00 | 2026-02-23 23:08:07.656431+00:00 | 2026-02-23 23:08:17.352726+00:00 |
| -894,000 | 2026-02-23 23:08:17+00:00 | 2026-02-23 23:08:07.656867+00:00 | 2026-02-23 23:08:17.351395+00:00 |
| -893,000 | 2026-02-23 23:08:17+00:00 | 2026-02-23 23:08:07.656925+00:00 | 2026-02-23 23:08:17.465098+00:00 |

```
| -964,000 | 2026-02-23 23:08:17+00:00 | 2026-02-23 23:08:07.653807+00:00 | 2026-02-23 23:08:17.443776+00:00 |

rtt   = 193,119 us
rtt/2 = 96,559.5 us

Received first :17 at :17.443776
So that was sent at  :17.443776 - .096 = :17.347

so they are 17.3ms slow
```

---

## Vanderbilt has a bad clock?

| offset_micros | server | send_at | receive_at |
| ---: | --- | --- | --- |
| -16,000  | 2026-02-23 23:16:41+00:00 | 2026-02-23 23:18:05.984000+00:00 | 2026-02-23 23:18:05.994490+00:00 |
| -15,000  | 2026-02-23 23:16:41+00:00 | 2026-02-23 23:18:05.985001+00:00 | 2026-02-23 23:18:05.995834+00:00 |
| -14,000  | 2026-02-23 23:16:41+00:00 | 2026-02-23 23:18:05.986000+00:00 | 2026-02-23 23:18:05.997446+00:00 |
| -13,000  | 2026-02-23 23:16:41+00:00 | 2026-02-23 23:18:05.987000+00:00 | 2026-02-23 23:18:05.997361+00:00 |
| -10,000  | 2026-02-23 23:16:41+00:00 | 2026-02-23 23:18:05.990001+00:00 | 2026-02-23 23:18:06.024230+00:00 |
| -9,000   | 2026-02-23 23:16:41+00:00 | 2026-02-23 23:18:05.991000+00:00 | 2026-02-23 23:18:06.033304+00:00 |
| -8,000   | 2026-02-23 23:16:41+00:00 | 2026-02-23 23:18:05.992001+00:00 | 2026-02-23 23:18:06.032646+00:00 |
| -6,000   | 2026-02-23 23:16:41+00:00 | 2026-02-23 23:18:05.994001+00:00 | 2026-02-23 23:18:06.006048+00:00 |
| -5,000   | 2026-02-23 23:16:41+00:00 | 2026-02-23 23:18:05.995000+00:00 | 2026-02-23 23:18:06.005162+00:00 |
| -3,000   | 2026-02-23 23:16:41+00:00 | 2026-02-23 23:18:05.997000+00:00 | 2026-02-23 23:18:06.009597+00:00 |
| -2,000   | 2026-02-23 23:16:41+00:00 | 2026-02-23 23:18:05.998000+00:00 | 2026-02-23 23:18:06.009544+00:00 |
| -1,000   | 2026-02-23 23:16:41+00:00 | 2026-02-23 23:18:05.999000+00:00 | 2026-02-23 23:18:06.009141+00:00 |
| 1,000    | 2026-02-23 23:16:41+00:00 | 2026-02-23 23:18:06.001001+00:00 | 2026-02-23 23:18:06.018222+00:00 |
| -215,000 | 2026-02-23 23:18:05+00:00 | 2026-02-23 23:18:05.785001+00:00 | 2026-02-23 23:18:05.805260+00:00 |
| -208,000 | 2026-02-23 23:18:05+00:00 | 2026-02-23 23:18:05.792001+00:00 | 2026-02-23 23:18:05.806245+00:00 |
| -207,000 | 2026-02-23 23:18:05+00:00 | 2026-02-23 23:18:05.793001+00:00 | 2026-02-23 23:18:05.806786+00:00 |
| -193,000 | 2026-02-23 23:18:05+00:00 | 2026-02-23 23:18:05.807001+00:00 | 2026-02-23 23:18:05.820055+00:00 |
| -192,000 | 2026-02-23 23:18:05+00:00 | 2026-02-23 23:18:05.808001+00:00 | 2026-02-23 23:18:05.820048+00:00 |
| -183,000 | 2026-02-23 23:18:05+00:00 | 2026-02-23 23:18:05.817001+00:00 | 2026-02-23 23:18:05.828291+00:00 |
